from django.urls import path
from mainapp import views
from testapp import views as viewstestapp
from testapp import views2 as views2testapp
from testapp import  qms_views,pharmacyviews
from usermanagementapp import views as usermanagement

urlpatterns = [
    path("",views.sign_up,name="sign_up"),
    path("create_tenants",views.create_tenants,name="create_tenants"),
    path('user_login',views.user_login_main,name='user_login_main'),
    path('branch_restrict',viewstestapp.branch_restrict,name='branch_restrict'),
    path('create_userprofile',views.create_userprofile,name='userprofile'),
    path('view_create_userprofile',views.view_create_userprofile,name='view_create_userprofile'),
    path('edit_create_userprofile/<pk>',views.edit_create_userprofile,name='edit_create_userprofile'),
    path('search_create_user',views.search_create_user,name='search_create_user'),
    path('create_user_delete/<pk>',views.create_user_delete,name='create_user_delete'),
    path('login',views.log_out,name='log_out'),
    path('select_location', views.select_location, name='select_location'),
    path('dashboard',viewstestapp.dashboard,name='dashboard'),
    path('patient_search/',viewstestapp.patient_search),
    path('patient_view_ap',viewstestapp.patient_view),
    path('book-appointment',viewstestapp.book_appointment),
    path('doctor_dash',viewstestapp.doctor_dash),
    path('doctor_appointment',viewstestapp.doctor_appointment),
    path('appointment_list',viewstestapp.appointment_list),
    path('patient_list',viewstestapp.patient_list),
    path('prescription',viewstestapp.prescription),
    path('qms_dashboard',viewstestapp.qms_dashboard,name='qms_dashboard'),
    path('token_master_configuration',viewstestapp.token_master_configuration),#Done
    path('token_master_configuration/<pk>',viewstestapp.token_master_configuration_update),#Done
    path('token_creation',viewstestapp.token_creation),#Done
    path('token_creation2',viewstestapp.token_creation2),#Done
    path('token_slip_generation/<pk>',viewstestapp.token_slip_generation),#Done
    path('token_slip_generations',viewstestapp.token_slip_generations),#Done
    path('centralised_admin_view',viewstestapp.centralised_admin_view),#Most Done
    path('opd_reception_view',viewstestapp.opd_reception_view),
    path('admin-dashboard',viewstestapp.patient_dashboard),
    path('appointment_table', viewstestapp.list_of_appointment, name='delete-appointment'),
    path('doctor_table',viewstestapp.DoctorDashbordView.as_view(),name='delete'),
    # Masters

    path('title_master',viewstestapp.title_master),
    path('template_master',viewstestapp.template_master,name='template_master'),
    path('hospital-master',viewstestapp.hospital_master),
    path('holiday_master',viewstestapp.holiday_master),
    path('edit_holiday_master',viewstestapp.edit_holiday_master),
    path('edit_holiday_master/<pk>',viewstestapp.editing_holiday_master),
    path('gender_master',viewstestapp.gender_master),
    path('add-new-gender-master',viewstestapp.add_new_gender_master),
    path('edit-gender-master',viewstestapp.edit_gender_master),
    path('editing-gender-master/<pk>',viewstestapp.editing_gender_master),
    path('district',viewstestapp.district),
    path('edit-district',viewstestapp.edit_district),
    path('editing-district/<pk>',viewstestapp.editing_district),
    path('country_master',viewstestapp.country_master),
    path('edit-country',viewstestapp.edit_country_master),
    path('editing-country/<pk>',viewstestapp.editing_country_master),
    path('city_master',viewstestapp.city_master),
    path('edit_city_master',viewstestapp.edit_city_master),
    path('editing_city_master/<pk>',viewstestapp.editing_city_master),
    path('most_common_document',viewstestapp.most_common_document),
    path('edit_most_common_document',viewstestapp.edit_most_common_document),
    path('editing_most_common_document/<pk>',viewstestapp.editing_most_common_document),
    path('maritial_status',viewstestapp.maritial_status),#Done
    path('edit_maritial_status',viewstestapp.edit_maritial_status),
    path('editing_maritial_status/<pk>',viewstestapp.editing_maritial_status),
    path('relation',viewstestapp.relation),#Done
    path('edit_relation',viewstestapp.edit_relation),
    path('editing_relation/<pk>',viewstestapp.editing_relation),
    path('group_master',viewstestapp.group_master),
    path('create-room',viewstestapp.create_room),
    path('branch_master',viewstestapp.branch_master),
    path('visit_type_master',viewstestapp.visit_type_master),
    path('service-master',viewstestapp.add_service_master),
    path('add_sub_service_master',viewstestapp.add_sub_service_master),
    path('add_service_department',viewstestapp.add_service_department),
    path('add_service_sub_department', viewstestapp.add_service_sub_department),
    path('edit_add_service_sub_department', viewstestapp.edit_add_service_sub_department),
    path('editing_add_sub_service_department/<int:id>', viewstestapp.editing_add_service_sub_department),
    path('ward_type',viewstestapp.ward_type),
    path('edit_ward_type', viewstestapp.edit_ward_type),
    path('editing_ward_type/<int:id>', viewstestapp.editing_ward_type),
    path('ward_category',viewstestapp.ward_category),
    path('blood_master', viewstestapp.blood_master),
    path('edit_blood_master', viewstestapp.edit_blood_master),
    path('editing_blood_master/<int:id>', viewstestapp.editing_blood_master),
    path('clinical_department',viewstestapp.clinical_department),
    path('edit_clinical_department',viewstestapp.edit_clinical_department),
    path('editing_clinical_department/<int:id>',viewstestapp.editing_clinical_department),
    path('designation',viewstestapp.designation),
    path('payment_mode', viewstestapp.payment_mode),
    path('edit_payment_mode', viewstestapp.edit_payment_mode),
    path('editing_payment_mode/<str:pk>/', viewstestapp.editing_payment_mode),
    path('bank_master', viewstestapp.bank_master),
    path('edit_bank_master', viewstestapp.edit_bank_master),
    path('editing_bank_master/<str:pk>/', viewstestapp.editing_bank_master),
    path('diagnosis_master',viewstestapp.diagnosis_master),
    path('ins_document', viewstestapp.ins_document, name='ins_document'),
    path('location_master', viewstestapp.location_master, name='location_master'),
    path('edit_location_master/<pk>',viewstestapp.edit_location_master,name='edit_location_master'),
    path('refered_bymaster', viewstestapp.refered_bymaster, name="refered_bymaster"),
    path('edit_refered_bymaster/<pk>',viewstestapp.edit_refered_bymaster,name = "edit_refered_bymaster"),
    path('relation_nhif',viewstestapp.relation_nhif,name = "relation_nhif"),
    path('edit_relation_nhif/<pk>',viewstestapp.edit_relation_nhif,name = "edit_relation_nhif"),
    path('main_dashboard',views2testapp.main_dashboard,name="main_dashboard"),

# =================================================================================================================

    path('patient_view_ap',viewstestapp.patient_view),
    path('book-appointment',viewstestapp.book_appointment),
    path('book-appointment/<int:npp>',viewstestapp.book_appointment),
    path('mobile_register',viewstestapp.mobile_register),
    path('date_time',viewstestapp.date_time),
    path('appointment_detail',viewstestapp.appointment_detail),
    path('booking_detail',viewstestapp.booking_detail),
    path('doctor-view',viewstestapp.doctor_view),
    path('doctor-schedule-view',viewstestapp.doctor_schedule_view),
    path('appointment-view',viewstestapp.appointment_view),
    path('patient-view',viewstestapp.patient_view_detail),
    path('admin_list_table',viewstestapp.admin_list_table),
    path('patient_table',viewstestapp.patient_table),
    path('doctor_table',viewstestapp.DoctorDashbordView.as_view(),name='delete'),
    path('edit-doctor/<str:pk>',viewstestapp.DoctorEditView.as_view()),
    path('detail-doctor/<str:pk>',viewstestapp.DoctorDetailView.as_view()),
    path('delete-appointment/<str:pk>',viewstestapp.AppointmentDeleteView.as_view()),
    path('detail-appointment/<str:pk>',viewstestapp.AppointmentDetailView.as_view()),
    path('success-booked',viewstestapp.success_booked),
    path('doctor-schedule',viewstestapp.doctor_schedule_view),
    path('schedule-date',viewstestapp.schedule_date),
    path('time-scheduling',viewstestapp.time_scheduling),
    path('scheduled_time',viewstestapp.scheduled_time),
    #cancel appointment
    path('cancel-appointment/<str:patient_id>',viewstestapp.cancel_appointment),
    #Appointment_dashboard
    path('doctor_dash',viewstestapp.doctor_dash),
    path('doctor_appointment',viewstestapp.doctor_appointment),
    path('prescription',viewstestapp.prescription),
    path('appointment_list',viewstestapp.appointment_list),
    path('patient_list',viewstestapp.patient_list),
    #Interface
    path('interface_dashboard',viewstestapp.interface_dashboard),
    path('patient',viewstestapp.patient),
    path('lo_g_in',viewstestapp.login),
    path('table',viewstestapp.table),
    #reports
    path('reports',viewstestapp.reports),
    path('cancellation-reports',viewstestapp.cancellation_reports),
    path('shorting-filter',viewstestapp.shorting_filter),
    path('appointment-detail-reports',viewstestapp.appointment_detail_reports),
    #doctor-admin pannel
    path('doctor-admin-pannel',viewstestapp.doctor_admin_pannel),
    path('create-admin',viewstestapp.sign_up_form),
    #=======New Appointment======
    path('filtering-department',viewstestapp.filtering_department),

    #===========QMS=======================
    # path('qms',qms_views.Token_Master_Cofiguration.as_view()),
    path('qms/',qms_views.Token_Master_Cofiguration_Class.as_view()),
    path('qms/<pk>',qms_views.Token_Master_Cofiguration_ClassRUD.as_view()),
    path('qms-token-master',qms_views.Token_Master_Cofiguration_view.as_view()),

    #==========title master======================
    path('titile-master',viewstestapp.titile_master),
    path('add-new-title',viewstestapp.add_new_title),
    path('edit-title',viewstestapp.edit_title),
    path('edit-title/<pk>',viewstestapp.editing_title),
    path('hospital-master',viewstestapp.hospital_master),
    path('add-new-hospital',viewstestapp.add_new_hospital),
    path('edit-hospital-master',viewstestapp.edit_hospital_master),
    path('edit-hospital-master/<pk>',viewstestapp.editing_hospital_master),
    path('add-new-gender-master',viewstestapp.add_new_gender_master),
    path('edit-gender-master',viewstestapp.edit_gender_master),
    path('editing-gender-master/<pk>',viewstestapp.editing_gender_master),
    path('holiday_master',viewstestapp.holiday_master),
    path('edit_holiday_master',viewstestapp.edit_holiday_master),
    path('edit_holiday_master/<pk>',viewstestapp.editing_holiday_master),
    path('most_common_document',viewstestapp.most_common_document),
    path('edit_most_common_document',viewstestapp.edit_most_common_document),
    path('editing_most_common_document/<pk>',viewstestapp.editing_most_common_document),
    #Master related urls
    #General_master
    path('title_master',viewstestapp.title_master),#Done
    # path('hospital_master',viewstestapp.hospital_master),
    path('relation',viewstestapp.relation),#Done
    path('edit_relation',viewstestapp.edit_relation),
    path('editing_relation/<pk>',viewstestapp.editing_relation),
    path('city_master',viewstestapp.city_master),
    path('edit_city_master',viewstestapp.edit_city_master),
    path('editing_city_master/<pk>',viewstestapp.editing_city_master),
    path('country_master',viewstestapp.country_master),
    path('edit-country',viewstestapp.edit_country_master),
    path('editing-country/<pk>',viewstestapp.editing_country_master),
    path('district',viewstestapp.district),
    path('edit-district',viewstestapp.edit_district),
    path('editing-district/<pk>',viewstestapp.editing_district),
    path('gender_master',viewstestapp.gender_master),#Done
    path('maritial_status',viewstestapp.maritial_status),#Done
    path('edit_maritial_status',viewstestapp.edit_maritial_status),
    path('editing_maritial_status/<pk>',viewstestapp.editing_maritial_status),
    #Service Master
    path('service_master',viewstestapp.service_master),
    path('edit_service_master/<pk>',viewstestapp.edit_service_master),
    path('tariff_master',viewstestapp.tariff_master),
    path('edit_tariff_master',viewstestapp.edit_tariff_master),
    path('edit_billing_master',viewstestapp.edit_billing_master),
    path('editing_billing_master/<int:id>',viewstestapp.editing_billing_master),
    path('editing_tariff_master/<pk>',viewstestapp.editing_tariff_master),
    path('corporate_master',viewstestapp.corporate_master),
    path('edit_corporate_master',viewstestapp.edit_corporate_master),
    path('editing_corporate_master/<pk>',viewstestapp.editing_corporate_master),
    path('billing_master',viewstestapp.billing_master),
    path('tariff_charge_master',viewstestapp.tariff_charge_master),
    path('edit_tariff_charge_master',viewstestapp.edit_tariff_charge_master),
    path('editing_tariff_charge_master/<pk>',viewstestapp.editing_tariff_charge_master),
    path('add_charge',viewstestapp.add_charge),
    path('billing_group_tariff',viewstestapp.billing_group_tariff),
    path('master-dashboard',viewstestapp.master_dashboard),
    #==============Advance QMS Master=====================
    path('service-master',viewstestapp.add_service_master),
    path('add_sub_service_master',viewstestapp.add_sub_service_master),
    path('add_service_department',viewstestapp.add_service_department),
    path('add_service_sub_department', viewstestapp.add_service_sub_department),
    path('edit_add_service_sub_department', viewstestapp.edit_add_service_sub_department),
    path('editing_add_sub_service_department/<int:id>', viewstestapp.editing_add_service_sub_department),
    path('ward_category',viewstestapp.ward_category),
    path('ward_type',viewstestapp.ward_type),
    path('edit_ward_type', viewstestapp.edit_ward_type),
    path('editing_ward_type/<int:id>', viewstestapp.editing_ward_type),
    path('blood_master', viewstestapp.blood_master),
    path('edit_blood_master', viewstestapp.edit_blood_master),
    path('editing_blood_master/<int:id>', viewstestapp.editing_blood_master),
    path('designation',viewstestapp.designation),
    # ===============diagnosis master===================
    path('diagnosis_master',viewstestapp.diagnosis_master),
    #==============URL FOR QMS=====================
    path('qms_dashboard',viewstestapp.qms_dashboard,name='qms_dashboard'),#Done
    path('token_master_configuration',viewstestapp.token_master_configuration),#Done
    path('token_master_configuration/<pk>',viewstestapp.token_master_configuration_update),#Done
    path('token_creation',viewstestapp.token_creation),#Done
    path('token_creation2',viewstestapp.token_creation2),#Done
    path('token_slip_generation/<pk>',viewstestapp.token_slip_generation),#Done
    path('token_slip_generations',viewstestapp.token_slip_generations),#Done
    path('centralised_admin_view',viewstestapp.centralised_admin_view),#Most Done
    path('opd_reception_view',viewstestapp.opd_reception_view),
    

    #==============Advance QMS Master=====================
    path('create-room',viewstestapp.create_room),
    # Clinical Dashboard (Main DashBoard)
    path('dashboard',viewstestapp.dashboard,name='dashboard'),
    path('partially_dashboard',viewstestapp.partially_dashboard),
    path('patient_registration/',viewstestapp.patient_registration),
    path('patient_registration/<str:uhid>',viewstestapp.patient_registration_edit),
    path('appoint_patient_register/<pk>',viewstestapp.appoint_patient_register,name="appoint_patient_register"),
    path('register_card/',viewstestapp.register_card),
    path('register_card/<str:uhid>',viewstestapp.register_card_generation),
    path('patient_visit/',viewstestapp.patient_visit),
    path('nursing_assessment/<str:data>', viewstestapp.nursing_assessment),
    path('consultant_tab_cancel/<pk>',viewstestapp.consultant_tab_cancel,name="consultant_tab_cancel"),
    path('investigation_cancel/<pk>', viewstestapp.investigation_cancel,name="investigation_cancel"),
    # path('nursing_assessment/',viewstestapp.nursing_assessment),
    path('opd_billing/',viewstestapp.opd_billing,name='ob'),
    path('opd_billing_search/<str:uhid>',viewstestapp.opd_billing),
    path('opd_billing_search',viewstestapp.opd_billing_search),
    path('visit_dashboard/',viewstestapp.visit_dashboard),
    path('opdbillrecipte/',viewstestapp.opdbillrecipte),
    # Image Uploading
    path('image_uploading',viewstestapp.image_uploading),
    path('patient_search/',viewstestapp.patient_search),
    path('patient_search_edit/<str:uhid>',viewstestapp.patient_search_edit),
    path('patient_search_delete/<str:uhid>',viewstestapp.patient_search_delete),
    path('out_paient_visit',viewstestapp.out_paient_visit),
    # Master
    path('branch_master',viewstestapp.branch_master),
    path('group_master',viewstestapp.group_master),
    path('visit_type_master',viewstestapp.visit_type_master),
    # Nurse Station
    path('nurse_dashboard/',viewstestapp.nurse_dashboard),
    path('nurse_login/',viewstestapp.nurse_login),
    path('emergency/',viewstestapp.emergency),
    path('in_patient_management/',viewstestapp.in_patient_management),
    path('procedure_room/',viewstestapp.procedure_room),
    path('system_control/',viewstestapp.system_control),
#     User Management
    path('billing_group_corporate',viewstestapp.billing_group_corporate),

    path('edit_wardcategory',viewstestapp.edit_wardcategory),
    path('editing_wardcategory/<pk>',viewstestapp.editing_wardcategory),
    path('intelligence_search',viewstestapp.intelligence_search),
#     Search Address
    path('search',viewstestapp.search_address,name='search'),
# Inventory

    path('item_master',viewstestapp.item_master),

    path('item_manufacturer',viewstestapp.item_manufacturer),
    path('store_nursing_counter_mapping',viewstestapp.store_nursing_counter_mapping),
    path('item_location_master',viewstestapp.item_location_master),
    path('multi_row',viewstestapp.multi_row),

#=====================Clinic Management================
    path('cm/<str:data>',viewstestapp.clinical_managements),
# ====================All Master Start==================
    path('visit_type_master',viewstestapp.visit_type_master),
    path('edit_visit_type_master',viewstestapp.edit_visit_type_master),
    path('editing_visit_type_master/<int:id>',viewstestapp.editing_visit_type_master),
    path('add_sub_service_master',viewstestapp.add_sub_service_master),
    path('edit_add_sub_service_master',viewstestapp.edit_add_sub_service_master),
    path('editing_add_sub_service_master/<int:id>',viewstestapp.editing_add_sub_service_master),
    path('add_service_department',viewstestapp.add_service_department),
    path('edit_add_service_department',viewstestapp.edit_add_service_department),
    path('editing_add_service_department/<int:id>',viewstestapp.editing_add_service_department),
    path('designation',viewstestapp.designation),
    path('edit_designation',viewstestapp.edit_designation),
    path('editing_designation/<int:id>',viewstestapp.editing_designation),
    path('clinical_department',viewstestapp.clinical_department),
    path('edit_clinical_department',viewstestapp.edit_clinical_department),
    path('editing_clinical_department/<int:id>',viewstestapp.editing_clinical_department),
    path('create-room',viewstestapp.create_room),
    path('edit_create_room',viewstestapp.edit_create_room),
    path('editing_create_room/<int:id>',viewstestapp.editing_create_room),
#======================All Master End======================
    path('temp_service_removing/<int:id>',viewstestapp.temp_service_removing,name='ser'),
    path('opd_trasaction',viewstestapp.opd_trasaction,name='opd_trasaction'),
# =================== by mantu ===================
    path('opd_payment_mode', viewstestapp.opd_payment_mode),
    path('opd_payment_credit', viewstestapp.opd_payment_credit),
    path('service_charge_master', viewstestapp.service_charge_master),
    path('main_opd', viewstestapp.main_opd),
    # path('delete_everything', viewstestapp.delete_everything),
    path('ipd', viewstestapp.ipd_list),
    path('summerize_bill', viewstestapp.summerize_bill),
    path('details_bill', viewstestapp.details_bill),
    path('payment_mode', viewstestapp.payment_mode),
    path('edit_payment_mode', viewstestapp.edit_payment_mode),
    path('editing_payment_mode/<str:pk>/', viewstestapp.editing_payment_mode),
    path('bank_master', viewstestapp.bank_master),
    path('edit_bank_master', viewstestapp.edit_bank_master),
    path('editing_bank_master/<str:pk>/', viewstestapp.editing_bank_master),
    path('investigation_view', viewstestapp.investigation_view),
    path('get_list_patient', viewstestapp.get_list_patient),
    path('get_list_patient_edit/<str:uhid>/', viewstestapp.get_list_patient_edit),
    path('avd_pay_paient_visit', viewstestapp.avd_pay_paient_visit),
    # date 10/11/22=====================
    path('hospital_report_revenue', viewstestapp.hospital_report_revenue),
    path('department_wise_reports', viewstestapp.department_wise_reports),
    path('patient_details', viewstestapp.patient_details),
    path('detail_revenue_report', viewstestapp.detail_revenue_report),
    path('hospital_department_report', viewstestapp.hospital_department_report),
    path('all_details_report', viewstestapp.all_details_report),
    path('doctor_wise_revenue_report', viewstestapp.doctor_wise_revenue_report),
    path('service_analysis_report', viewstestapp.service_analysis_report),
    path('detail_doctor_report', viewstestapp.detail_doctor_report),
    path('today_report', viewstestapp.today_report),
    path('credit_bill', viewstestapp.credit_bill),
    path('credit_patient', viewstestapp.credit_patient),
    path('outstannding_amt_register', viewstestapp.outstannding_amt_register),
    path('payer_by_report', viewstestapp.payer_by_report),
    path('report_datewise_bill', viewstestapp.report_datewise_bill),
    path('mode_of_payment', viewstestapp.mode_of_payment),
    # ============== opd package  =============
    path('opd_package_master', viewstestapp.opd_package_master, name='opd_package_master'),
    path('opd_package_master_view', viewstestapp.opd_package_master_view, name='opd_package_master_view'),
    path('opd_package_master_edit/<pk>', viewstestapp.opd_package_master_edit, name='opd_package_master_edit'),
    path('opd_package_service', viewstestapp.opd_package_service, name='opd_package_service'),
    path('opd_package_service_add', viewstestapp.opd_package_service_add, name='opd_package_service_add'),
    path('opd_package_service_temp/<serv>', viewstestapp.opd_package_service_temp, name='opd_package_service_temp'),

    #====================== API Karan 31/12/22 =====================
    path('api_medication', viewstestapp.api_medication),
    path('api_medication_view', viewstestapp.api_medication_view),
    path('api_PatientsRegistration/<pk>', viewstestapp.api_PatientsRegistration),
    path('api_PatientsRegistration_view', viewstestapp.api_PatientsRegistration_view),
    path('admissioninfo_all', viewstestapp.admissioninfo_all),

    # ===================== For Bed Karan =====================
    path('bed_view', viewstestapp.bed_view),
    # path('bed_load', viewstestapp.bed_load, name='bed_load'),
    path('bed_load', viewstestapp.bed_load, name='test_app_bed_load'),

    path('doctor_ability_report', viewstestapp.doctor_ability_report, name='doctor_ability_report'),
    path('bed_charge', viewstestapp.bed_charge, name='bed_charge'),
    path('single_bed_charge_load', viewstestapp.single_bed_charge_load, name='single_bed_charge_load'),
    path('Bed_charge_edit', viewstestapp.Bed_charge_edit, name='Bed_charge_edit'),

    path('bed_charge_slip', viewstestapp.bed_charge_slip, name='bed_charge_slip'),
    path('bed_charge_slip_details/<pk>', viewstestapp.bed_charge_slip_details, name='bed_charge_slip_details'),
    path('charge_slip_load', viewstestapp.charge_slip_load, name='charge_slip_load'),
    path('bed_charge_slip_details_edit/<pk>', viewstestapp.bed_charge_slip_details_edit, name='bed_charge_slip_details_edit'),
    path('bed_charge_slip_details_editing/<pk>', viewstestapp.bed_charge_slip_details_editing,
         name='bed_charge_slip_details_editing'),


    path('discharge_report', viewstestapp.discharge_report, name='discharge_report'),

#=============================== opd package link with tariff =======================
    path('link_opdpackage_tariff',viewstestapp.link_opdpackage_tariff),
    path('admission_load',viewstestapp.admission_load),
    path('load_ward_category',viewstestapp.load_ward_category),
    path('doctor_accounting',viewstestapp.doctor_accounting),
    path('dr_accounting_report',viewstestapp.dr_accounting_report),
    path('all_data_insert',viewstestapp.all_data_insert),

# Profile Master 14/12/22
    path('profile_master',viewstestapp.profile_master),
    path('profile_master_view',viewstestapp.profile_master_view),
    path('profile_master_edit/<pk>/',viewstestapp.profile_master_edit),
    path('profile_service', viewstestapp.profile_service, name='profile_service'),
    path('profile_service_add', viewstestapp.profile_service_add, name='profile_service_add'),
    path('profile_service_temp/<serv>', viewstestapp.profile_service_temp, name='profile_service_temp'),
    path('service_test1/<dep>/<subdep>/', viewstestapp.service_test_search, name='service_test_search'),
    path('service_test', viewstestapp.service_test, name='service_test'),
    path('service_test_range/<pk>/', viewstestapp.service_test_range, name='service_test_range'),
    path('service_test_range_edit/<pk>/', viewstestapp.service_test_range_edit, name='service_test_range_edit'),
    path('service_test_edit', viewstestapp.service_test_edit, name='service_test_edit'),
    path('service_test_editing/<pk>', viewstestapp.service_test_editing, name='service_test_editing'),
    path('profile_package_tarifflink', viewstestapp.profile_package_tarifflink, name='profile_package_tarifflink'),
    path('service_test_tarifflink', viewstestapp.service_test_tarifflink, name='service_test_tarifflink'),

    path('sample_master',viewstestapp.sample_master,name='sample_master'),
    path('volume_master',viewstestapp.volume_master,name='volume_master'),
    path('sample_master_edit',viewstestapp.sample_master_edit,name='sample_master_edit'),
    path('sample_master_editing/<pk>',viewstestapp.sample_master_editing,name='sample_master_editing'),
    path('volume_master_edit',viewstestapp.volume_master_edit,name='volume_master_edit'),
    path('volume_master_editing/<pk>',viewstestapp.volume_master_editing,name='volume_master_editing'),

    path('lab_pending_investigation',viewstestapp.lab_pending_investigation,name='lab_pending_investigation'),
    path('lab_sammple_collected',viewstestapp.lab_sammple_collected,name='lab_sammple_collected'),
    path('lab_result_entry/<pk>',viewstestapp.lab_result_entry,name='lab_result_entry'),
    path('result_validation',viewstestapp.result_validation,name='result_validation'),
    path('result_validation_view/<pk>',viewstestapp.result_validation_view,name='result_validation_view'),
    path('lab_report',viewstestapp.lab_report,name='lab_report'),
    path('lab_report_print/<pk>',viewstestapp.lab_report_print,name='lab_report_print'),
    path('dep_lab_report_print/<pk>',viewstestapp.dep_lab_report_print,name='dep_lab_report_print'),
    path('dep_lab_report',viewstestapp.dep_lab_report,name='dep_lab_report'),
    path('report_change/<pk>',viewstestapp.report_change,name='report_change'),

# ============== user management ====================



# ============== ward module =============
    path('paitent_ward',viewstestapp.paitent_ward,name='ward'),
    path('paitent_ward_actions/<str:pk>/',viewstestapp.paitent_ward_actions,name='paitent_ward_actions'),
    # path('medication/<pk>',viewstestapp.medication,name='medication'),
    # path('medication/<pk>/<med>',viewstestapp.medications,name='medication'),
    # path('investigation/<pk>',viewstestapp.investigation,name='investigation'),
    # path('investigation_insert/<pk>/<ser>',viewstestapp.investigation_insert,name='investigation_insert'),
    # path('consultation/<pk>',viewstestapp.consultation,name='consultation'),
    # path('consultation_insert/<pk>/<ser>',viewstestapp.consultation_insert,name='consultation_insert'),
    # path('procedure/<pk>',viewstestapp.procedure,name='procedure'),
    # path('procedure_insert/<pk>/<ser>',viewstestapp.procedure_insert,name='procedure_insert'),
    # 29/12/22 mantu ============================
    path('temp_records', viewstestapp.temp_records, name='temp_records'),
    path('opd_billing_temp/', viewstestapp.opd_billing_temp),
    # path('opd_billing_temp/<str:uhid>/', viewstestapp.opd_billing_temp),
    path('opd_billing_temp/<str:uhid>/<vis>', viewstestapp.opd_billing_temp, name='opd_billing_temp'),
    path('opdbill_all', viewstestapp.opdbill_all, name='opdbill_all'),

    # ================ Doctor Share with Package 27/12/22 ==================================
    path('dr_share_with_package', viewstestapp.dr_share_with_package),
    path('dr_share_with_profile', viewstestapp.dr_share_with_profile),
    path('composite_services', viewstestapp.composite_services),
    path('add_charge_profile', viewstestapp.add_charge_profile),
    path('package_services', viewstestapp.package_services),
    path('add_charge_package_services', viewstestapp.add_charge_package_services),
    path('belongs_to_master', viewstestapp.belongs_to_master),

    path('nursing_notes', viewstestapp.nursing_notes),
    path('view_nursing_notes/<pk>', viewstestapp.view_nursing_notes),

    #============= Dialysis Template ============= 23/01/23 ==========
    path('pre_dialysis_details/<pk>', viewstestapp.pre_dialysis_details),
    path('view_pre_dialysis_details/<pk>/', viewstestapp.view_pre_dialysis_details),
    path('post_dialysis_details/<pk>/', viewstestapp.post_dialysis_details,name='post_dialysis_details'),
    path('view_post_dialysis/<pk>/', viewstestapp.view_post_dialysis),
    path('dialysis_details/<pk>/', viewstestapp.dialysis_details),
    path('chemotherapy_treatment_sheet', viewstestapp.chemotherapy_treatment_sheet),
    path('view_chemotherapy/<pk>', viewstestapp.view_chemotherapy),
    #======================== GOKILA CODE ======================
    # Reports
    path('Patient_registration_report', viewstestapp.Patient_registration_report),
    path('Patient_registration_summery_report', viewstestapp.Patient_registration_summery_report),
    path('appointment_report', viewstestapp.appointment_report),
    path('patientvisit_report', viewstestapp.patientvisit_report),
    path('consultant_report', viewstestapp.consultant_report),
    path('grouping_admission_report', viewstestapp.grouping_admission_report),
    path('Bed_Transfer_report', viewstestapp.Bed_Transfer_report),
    path('bed_occupancy_report', viewstestapp.bed_occupancy_report),
    path('bed_load1', viewstestapp.bed_load1, name='bed_load1'),
    path('bedview',viewstestapp.bed_view),
    path('detail_bed_occupany_report', viewstestapp.detail_bed_occupany_report),
    # estimate ====================
    path('estimate',viewstestapp.estimate,name='estimate'),
    path('estimate_temp',viewstestapp.estimate_temp,name='estimate_temp'),
    path('estimate_sub_temp/<str:serv>/',viewstestapp.estimate_sub_temp,name='estimate_sub_temp'),
    path('estimate_pdf',viewstestapp.estimate_pdf,name='estimate_pdf'),

    path('dashboard_report',viewstestapp.dashboard_report,name='dashboard_report'),

    #======== Dialysis Master 01/02/2023 ================
    path('status_dialysis_view',viewstestapp.status_dialysis_view,name='status_dialysis_view'),
    path('status_dialysis',viewstestapp.status_dialysis,name='status_dialysis'),
    path('status_dialysis_edit/<pk>',viewstestapp.status_dialysis_edit,name='status_dialysis_edit'),
    path('primary_dialysis_theropist',viewstestapp.primary_dialysis_theropist,name='primary_dialysis_theropist'),
    path('primary_dialysis_theropist_view',viewstestapp.primary_dialysis_theropist_view,name='primary_dialysis_theropist_view'),
    path('primary_dialysis_theropist_edit/<pk>',viewstestapp.primary_dialysis_theropist_edit,name='primary_dialysis_theropist_edit'),
    path('secondry_dialysis_theropist',viewstestapp.secondry_dialysis_theropist,name='secondry_dialysis_theropist'),
    path('secondry_dialysis_theropist_view',viewstestapp.secondry_dialysis_theropist_view,name='secondry_dialysis_theropist_view'),
    path('secondry_dialysis_theropist_edit/<pk>',viewstestapp.secondry_dialysis_theropist_edit,name='secondry_dialysis_theropist_edit'),    path('secondry_dialysis_theropist',viewstestapp.secondry_dialysis_theropist,name='secondry_dialysis_theropist'),

    path('machine_name',viewstestapp.machine_name,name='machine_name'),
    path('machine_name_view',viewstestapp.machine_name_view,name='machine_name_view'),
    path('machine_name_edit/<pk>',viewstestapp.machine_name_edit,name='machine_name_edit'),
    path('asset_type',viewstestapp.asset_type,name='asset_type'),
    path('asset_type_view',viewstestapp.asset_type_view,name='asset_type_view'),
    path('asset_type_edit/<pk>',viewstestapp.asset_type_edit,name='asset_type_edit'),
    path('bruit_thrill',viewstestapp.bruit_thrill,name='bruit_thrill'),
    path('bruit_thrill_view',viewstestapp.bruit_thrill_view,name='bruit_thrill_view'),
    path('bruit_thrill_edit/<pk>',viewstestapp.bruit_thrill_edit,name='bruit_thrill_edit'),
    path('access_site',viewstestapp.access_site,name='access_site'),
    path('access_site_view',viewstestapp.access_site_view,name='access_site_view'),
    path('access_site_edit/<pk>',viewstestapp.access_site_edit,name='access_site_edit'),
    path('dialysis_type',viewstestapp.dialysis_type,name='dialysis_type'),
    path('dialysis_type_view',viewstestapp.dialysis_type_view,name='dialysis_type_view'),
    path('dialysis_type_edit/<pk>',viewstestapp.dialysis_type_edit,name='dialysis_type_edit'),
    path('completion_Status',viewstestapp.completion_Status,name='completion_Status'),
    path('completion_Status_view',viewstestapp.completion_Status_view,name='completion_Status_view'),
    path('completion_Status_edit/<pk>',viewstestapp.completion_Status_edit,name='completion_Status_edit'),
    path('needle_type',viewstestapp.needle_type,name='needle_type'),
    path('needle_type_view',viewstestapp.needle_type_view,name='needle_type_view'),
    path('needle_type_edit/<pk>',viewstestapp.needle_type_edit,name='needle_type_edit'),
    path('dialyzer',viewstestapp.dialyzer,name='dialyzer'),
    path('dialyzer_view',viewstestapp.dialyzer_view,name='dialyzer_view'),
    path('dialyzer_edit/<pk>',viewstestapp.dialyzer_edit,name='dialyzer_edit'),
    path('rating',viewstestapp.rating,name='rating'),
    path('rating_view',viewstestapp.rating_view,name='rating_view'),
    path('rating_edit/<pk>',viewstestapp.rating_edit,name='rating_edit'),
    path('anticoagulation',viewstestapp.anticoagulation,name='anticoagulation'),
    path('anticoagulation_view',viewstestapp.anticoagulation_view,name='anticoagulation_view'),
    path('anticoagulation_edit/<pk>',viewstestapp.anticoagulation_edit,name='anticoagulation_edit'),
    path('heparin_type',viewstestapp.heparin_type,name='heparin_type'),
    path('heparin_type_view',viewstestapp.heparin_type_view,name='heparin_type_view'),
    path('heparin_type_edit/<pk>',viewstestapp.heparin_type_edit,name='heparin_type_edit'),
    path('closing_attendent',viewstestapp.closing_attendent,name='closing_attendent'),
    path('closing_attendent_view',viewstestapp.closing_attendent_view,name='closing_attendent_view'),
    path('closing_attendent_edit/<pk>',viewstestapp.closing_attendent_edit,name='closing_attendent_edit'),
    path('shift', viewstestapp.shift, name='shift'),
    path('shift_view', viewstestapp.shift_view, name='shift_view'),
    path('shift_edit/<pk>', viewstestapp.shift_edit, name='shift_edit'),
    path('schedule_master', viewstestapp.schedule_master, name='schedule_master'),
    path('schedule_master_view', viewstestapp.schedule_master_view, name='schedule_master_view'),
    path('schedule_master_edit/<pk>', viewstestapp.schedule_master_edit, name='schedule_master_edit'),

    path('medical_equipment', viewstestapp.medical_equipment, name='medical_equipment'),
    path('medical_equipment_edit/<pk>', viewstestapp.medical_equipment_edit, name='medical_equipment_edit'),
    path('new_invoice', viewstestapp.new_invoice, name='new_invoice'),
    path('maintanence_deatils', viewstestapp.maintanence_deatils, name='maintanence_deatils'),
    path('mainmaintenance_pdf', viewstestapp.mainmaintenance_pdf, name='mainmaintenance_pdf'),
    path('unplanned_maintanence', viewstestapp.unplanned_maintanence, name='unplanned_maintanence'),
    path('unplanned_maintanence_pdf', viewstestapp.unplanned_maintanence_pdf, name='unplanned_maintanence_pdf'),
    path('preventory_maintanence', viewstestapp.preventory_maintanence, name='preventory_maintanence'),
    path('preventory_maintanence_pdf', viewstestapp.preventory_maintanence_pdf, name='preventory_maintanence_pdf'),
    path('validation_calibration', viewstestapp.validation_calibration, name='validation_calibration'),
    path('validation_calibration_pdf', viewstestapp.validation_calibration_pdf, name='validation_calibration_pdf'),
    path('get_report', viewstestapp.get_report, name='get_report'),
    path('ins_document', viewstestapp.ins_document, name='ins_document'),
    path('email_sending', viewstestapp.email_sending, name='email_sending'),
    path('send_email', viewstestapp.send_email, name='send_email'),
    path('veryf_otp', viewstestapp.veryf_otp, name='veryf_otp'),
    path('finalized_bill', viewstestapp.finalized_bill, name='finalized_bill'),
    path('closed_bill', viewstestapp.closed_bill, name='closed_bill'),
    path('cancel_bill', viewstestapp.cancel_bill, name='cancel_bill'),
    path('cancel_bill_store/<pk>', viewstestapp.cancel_bill_store, name='cancel_bill_store'),
    path('discharge_form', viewstestapp.discharge_form, name='discharge_form'),
    path('case_summery', viewstestapp.case_summery, name='case_summery'),
    path('consent_chemotherapy', viewstestapp.consent_chemotherapy, name='consent_chemotherapy'),
    path('refferal_form', viewstestapp.refferal_form, name='refferal_form'),
    path('print_consent_chemotherapy/<pk>', viewstestapp.print_consent_chemotherapy, name='print_consent_chemotherapy'),
    path('print_refferal_form/<pk>', viewstestapp.print_refferal_form, name='print_refferal_form'),
    path('print_case_summery/<pk>', viewstestapp.print_case_summery, name='print_case_summery'),
    path('for_open_bill_main_opd', viewstestapp.for_open_bill_main_opd, name='for_open_bill_main_opd'),
    path('discharge_list', viewstestapp.discharge_list, name='discharge_list'),
    path('discharge_report/<pk>', viewstestapp.discharge_report, name='discharge_report'),
    path('dep_lab_report_all', viewstestapp.dep_lab_report_all, name='dep_lab_report_all'),
    path('dep_lab_report_print_all/<pk>', viewstestapp.dep_lab_report_print_all, name='dep_lab_report_print_all'),
    path('send_email/<pk>', viewstestapp.send_email, name='send_email'),
    path('discharge_reportopd/<str:pk>', viewstestapp.discharge_reportopd, name='discharge_reportopd'),
    path('discharge_listopd', viewstestapp.discharge_listopd, name='discharge_listopd'),
    path('list_dialysis_patient', viewstestapp.list_dialysis_patient, name='list_dialysis_patient'),
    #========= Inventory Item Master =========================
    # path('inventory_itemmaster', viewstestapp.inventory_itemmaster, name='inventory_itemmaster'),
    path('main_dashboard',views2testapp.main_dashboard,name="main_dashboard"),
###--Insurance Module---###
    path('checklist_master',viewstestapp.checklist_master,name="checklist_master"),
    path('insurance_claim',viewstestapp.insurance_claim,name="insurance_claim"),
    path('checklisted_bill',viewstestapp.checklisted_bill,name="checklisted_bill"),
    path('claim_acknowledge/<bill_no>/',viewstestapp.claim_acknowledge,name="claim_acknowledge"),
    path('raising_queries/<bill_no>/',viewstestapp.raising_queries,name="raising_queries"),
    path('view_document_details/<bill_no>/',viewstestapp.view_document_details,name="view_document_details"),
    path('raising_queries_list',viewstestapp.raising_queries_list,name="raising_queries_list"),
    path('settled_claim_list',viewstestapp.settled_claim_list,name="settled_claim_list"),
    path('acknowledge_claim',viewstestapp.acknowledge_claim,name="acknowledge_claim"),
    path('payment_details_claim/<pk>/',viewstestapp.payment_details_claim,name="payment_details_claim"),
    path('save_claim_settle',viewstestapp.save_claim_settle,name="save_claim_settle"),
    path('queries_list/<bill_no>/',viewstestapp.queries_list,name="queries_list"),

#==============nephromed pharmacy===================

# Inventory
    path('store_master',viewstestapp.store_master),
    path('deleting_store_master/<id>',viewstestapp.deleting_store_master),
    path('inventory_itemmaster',viewstestapp.inventory_itemmaster),
    path('generic_master',viewstestapp.generic_master),
    path('vendor_master',viewstestapp.vendor_master , name='vendor_master'),
    path('item_category_master',viewstestapp.item_category_master),
    path('packaging_master',viewstestapp.packaging_master),
    path('item_unit_master',viewstestapp.item_unit_master),
    path('load_itemcategory',viewstestapp.load_itemcategory ,name='load_itemcategoryy'),
    path('itemsubcategory_master',viewstestapp.itemsubcategory_master),


    # Pharmacy
    path('pharmacy_dashboard',pharmacyviews.pharmacy_dashboard,name="pharmacy_dashboard"),
    path('purchase_order',pharmacyviews.purchase_order,name="purchase_order"),
    path('view_po_edit',pharmacyviews.view_po_edit,name="view_po_edit"),
    path('view_po_details/<pk>',pharmacyviews.view_po_details,name="view_po_details"),
    path('delete_po_child/<pk>',pharmacyviews.delete_po_child,name="delete_po_child"),
    path('edit_single_child',pharmacyviews.edit_single_child,name="edit_single_child"),
    path('purchaseorder_preview/<pk>',pharmacyviews.purchaseorder_preview,name="purchaseorder_preview"),
    path('PO_calculate',pharmacyviews.PO_calculate,name="calculate"),
    path('get_stock_details',pharmacyviews.get_stock_details,name="get_stock_details"),
    path('PO_preview',pharmacyviews.PO_preview,name="PO_preview"),
    path('PO_approval_preview',pharmacyviews.PO_approval_preview,name="PO_approval_preview"),
    path('purchase_order_approval',pharmacyviews.purchase_order_approval,name="purchase_order_approval"),
    path('PO_pending_update/<pk>/',pharmacyviews.PO_pending_update,name="PO_pending_update"),
    path('PO_approveview/<pk>/',pharmacyviews.PO_approveview,name="PO_approveview"),
    path('PO_update/',pharmacyviews.PO_update,name="PO_update"),
    path('email_sending',pharmacyviews.email_sending,name="email_sending"),
    path('stock_entry',pharmacyviews.stock_entry,name="stock_entry"),
    path('view_grn_edit',pharmacyviews.view_grn_edit,name="view_grn_edit"),
    path('grn_preview/<pk>/',pharmacyviews.grn_preview,name="grn_preview"),
    path('search_single_PO/<pk>/',pharmacyviews.search_single_PO,name="search_single_PO"),
    path('SE_preview',pharmacyviews.SE_preview,name="SE_preview"),
    path('Without_PO',pharmacyviews.SE_without_po,name="SE_without_po"),
    path('vendor_payment',pharmacyviews.vendor_payment,name="vendor_payment"),
    path('vendor_payment_js',pharmacyviews.vendor_payment_js,name="vendorpaymentjs"),
    path('item_issue_to_mainstore',pharmacyviews.item_issue_to_mainstore,name="item_issue_to_mainstore"),
    path('view_cpcstore_stock',pharmacyviews.view_cpcstore_stock,name="view_cpcstore_stock"),
    path('item_issue_tomainstore/<po_id>',pharmacyviews.item_issue_tomainstore,name="item_issue_tomainstore"),
    path('search_batch_intent_JQ',pharmacyviews.search_batch_intent_JQ,name="search_batch_intent_JQ"),
    path('without_po_entry',pharmacyviews.without_po_entry,name="without_po_entry"),
    path('item_issue_tomainstore_withoutpo/<pk>',pharmacyviews.item_issue_tomainstore_withoutpo,name="item_issue_tomainstore_withoutpo"),
    path('material_indent',pharmacyviews.material_indent,name="material_intent"),
    path('view_mi_edit',pharmacyviews.view_mi_edit,name="view_mi_edit"),
    path('view_mi_details/<pk>',pharmacyviews.view_mi_details,name="view_mi_details"),
    path('edit_single_michild',pharmacyviews.edit_single_michild,name="edit_single_michild"),
    path('meterial_intent_JS',pharmacyviews.meterial_intent_JS,name="meterial_intent_JS"),
    path('material_indent_approval',pharmacyviews.material_indent_approval,name="material_indent_approval"),
    path('material_indent_item_detail/<indent_id>',pharmacyviews.material_indent_item_detail,name="material_indent_item_detail"),
    path('materialindent_approve_item_detail/<indent_id>',pharmacyviews.materialindent_approve_item_detail,name="materialindent_approve_item_detail"),
    path('indent_inbox',pharmacyviews.indent_inbox,name="indent_inbox"),
    path('item_issue',pharmacyviews.item_issue,name="item_issue"),
    path('view_mainstore_stock',pharmacyviews.view_mainstore_stock,name="view_mainstore_stock"),
    path('WO_intent',pharmacyviews.WO_intent,name="WO_intent"),
    path('search_mainstore_batchno',pharmacyviews.search_mainstore_batchno,name="search_mainstore_batchno"),
    path('without_JQ_mainstore',pharmacyviews.without_JQ_mainstore,name="without_JQ_mainstore"),
    path('without_JQ',pharmacyviews.without_JQ,name="without_JQ"),
    path('search_material_intent/<pk>/',pharmacyviews.search_material_intent,name="search_material_intent"),
    path('search_material_intent_JQ',pharmacyviews.search_material_intent_JQ,name="search_material_intent_JQ"),
    path('item_return',pharmacyviews.item_return,name="item_return"),
    path('item_return_JS',pharmacyviews.item_return_JS,name="itemreturnJS"),
    path('item_return_to_cpc',pharmacyviews.item_return_to_cpc,name="item_return_to_cpc"),
    path('return_to_cpc_js',pharmacyviews.return_to_cpc_js,name="return_to_cpc_js"),
    path('mainstore_makereturn',pharmacyviews.mainstore_makereturn,name="mainstore_makereturn"),
    path('item_return_supplier',pharmacyviews.item_return_supplier,name="item_return_supplier"),
    path('STV_makereturn',pharmacyviews.STV_makereturn,name="STV_makereturn"),
    path('purchase_intent',pharmacyviews.purchase_intent,name="purchase_intent"),
    path('purchase_intent_approval',pharmacyviews.purchase_intent_approval,name="purchase_intent_approval"),
    path('purchaseindent_approve_item_detail/<indent_id>',pharmacyviews.purchaseindent_approve_item_detail,name="purchaseindent_approve_item_detail"),
    path('PI_pending_update/<pk>/',pharmacyviews.PI_pending_update,name="PI_pending_update"),
    path('PI_update',pharmacyviews.PI_update,name="PI_update"),
    path('make_PO_for_PI/',pharmacyviews.make_PO_for_PI,name="make_PO_for_PI"),
    path('PI_items_details/<pk>/',pharmacyviews.PI_items_details,name="PI_items_details"),
    path('Manual_stock_adjustment',pharmacyviews.manual_stock_adjustment,name="Manual_stock_adjustment"),
    path('Single_update_adjustment',pharmacyviews.Single_update_adjustment,name="Single"),
    path('file_upload',pharmacyviews.file_upload,name="fileupload"),
    path('PO_approval_sendmail',pharmacyviews.PO_approval_sendmail,name="mailsending"),
    path('return_to_supplier_js',pharmacyviews.return_to_supplier_js,name="returntosupplierjs"),
    path('patient_feedback',pharmacyviews.patient_feedback,name="patient_feedback"),
    path('get_uhid_detail',pharmacyviews.get_uhid_detail,name="get_uhid_detail"),
    path('patient_feedback_report',pharmacyviews.patient_feedback_report,name="patient_feedback_report"),
    path('viewPO_in_poapproval',pharmacyviews.viewPO_in_poapproval,name="viewPO_in_poapproval"),
    path('viewPO_details/<pk>/',pharmacyviews.viewPO_in_poapproval_details,name="viewPO_details"),
    path('department_consump_search',pharmacyviews.department_consump_search,name="department_consump_search"),
    path('department_consump',pharmacyviews.department_consump,name="department_consump"),
    path('save_department_consume',pharmacyviews.save_department_consume,name="save_department_consume"),
    path('transfer_indent',pharmacyviews.transfer_indent,name="transfer_indent"),
    path('stock_transfer',pharmacyviews.stock_transfer,name="stock_transfer"),
    path('search_transfer_intent/<pk>/',pharmacyviews.search_transfer_intent,name="search_transfer_intent"),
    path('transfer_request_tomainstore',pharmacyviews.transfer_request_tomainstore,name="transfer_request_tomainstore"),
    path('search_transfer_item_detail/<pk>/',pharmacyviews.search_transfer_item_detail,name="search_transfer_item_detail"),
    path('transfer_to_cpc',pharmacyviews.transfer_to_cpc,name="transfer_to_cpc"),
    path('request_transfer_item_list/<pk>/',pharmacyviews.request_transfer_item_list,name="request_transfer_item_list"),
    path('search_batch_indent_JQ',pharmacyviews.search_batch_indent_JQ,name="search_batch_indent_JQ"),
    path('without_indent_stock_transfer',pharmacyviews.without_indent_stock_transfer,name="without_indent_stock_transfer"),
    path('searchbatchno_mainstore',pharmacyviews.searchbatchno_mainstore,name="searchbatchno_mainstore"),
    path('returntosupplier_preview',pharmacyviews.returntosupplier_preview,name="returntosupplier_preview"),
    path('returntosupplier_sendmail',pharmacyviews.returntosupplier_sendmail,name="returntosupplier_sendmail"),

    # pharmacy sales

    path('add_counter_saleout_patient',pharmacyviews.add_counter_saleout_patient,name="counter_saleout_patient"),
    path('add_count_sale_js',pharmacyviews.add_count_sale_js,name="add_count_sale"),
    path('delete_pharmacy_temp',pharmacyviews.delete_pharmacy_temp,name="delete_pharmacy_temp"),
    path('delete_pharmacy_otctemp',pharmacyviews.delete_pharmacy_otctemp,name="delete_pharmacy_otctemp"),
    path('payment_detail_sale/<pk>',pharmacyviews.payment_detail_sale,name="payment_detail_sale"),
    path('payment_mode_detail/<pk>',pharmacyviews.payment_mode_detail,name="payment_mode_detail"),
    path('prescription_details/<pk>',pharmacyviews.prescription_details,name="prescription_details"),
    path('bill_generate_search',pharmacyviews.bill_generate_search,name="bill_generate_search"),
    path('generate_bill/<pk>',pharmacyviews.generate_bill,name="generate_bill"),
    path('not_bill_generate_search',pharmacyviews.not_bill_generate_search,name="not_bill_generate_search"),
    path('prescriped_details/<pk>',pharmacyviews.prescriped_details,name="prescriped_details"),
    path('prescription_list',pharmacyviews.prescription_list,name="prescription_list"),    path('searchitemname',pharmacyviews.searchitemname,name="searchitemname"),
    path('search_batchno',pharmacyviews.search_batchno,name="searchbatchno"),
    path('get_patientregistration_js',pharmacyviews.get_patientregistration_js,name="patientregistration"),
    path('add_counter_saleout_patient_preview',pharmacyviews.add_counter_saleout_patient_preview,name="saleoutpatientpreview"),
    path('sales_return_from_OP',pharmacyviews.sales_return_from_OP,name="sales_return_from_OP"),
    path('sales_return_from_OP_1',pharmacyviews.sales_return_from_OP_1,name="sales_return_from_OP_1"),
    path('sales_return_from_OP_invoice/<pk>',pharmacyviews.sales_return_from_OP_invoice,name="sales_return_OPinvoice"),
    path('status_update_to_PS',pharmacyviews.status_update_to_PS,name="status_updatePS"),
    path('status_update_to_PSR',pharmacyviews.status_update_to_PSR,name="status_updatePSR"),

    path('department_consump_search',pharmacyviews.department_consump_search,name="department_consump_search"),
    path('department_consump',pharmacyviews.department_consump,name="department_consump"),
    path('ward_request', pharmacyviews.ward_request, name="ward_request"),
    path('ward_sales/<medid>', pharmacyviews.ward_sales, name="ward_sales"),

    # Pharmacy Reports

    path('item_status_report',pharmacyviews.item_status_report,name="item_status_report"),
    path('PO_report',pharmacyviews.PO_report,name="PO_report"),
    path('PO_report_pk/<pk>/',pharmacyviews.PO_report_pk,name="PO_report_pk"),
    path('batchwise_report',pharmacyviews.batchwise_report,name="batchwise_report"),
    path('po_status_report',pharmacyviews.po_status_report,name="po_status_report"),
    path('po_supplier_wise_search',pharmacyviews.po_supplier_wise_search,name="po_supplier_wise_search"),
    path('po_supplier_wise_report/<pk>',pharmacyviews.po_supplier_wise_report,name="po_supplier_wise_report"),
    path('po_aging_report',pharmacyviews.po_aging_report,name="po_aging_report"),
    path('po_item_details_report/<pk>',pharmacyviews.po_item_details_report,name="po_item_details_report"),
    path('item_issue_details/<pk>',pharmacyviews.item_issue_details,name="item_issue_details"),
    path('item_issue_report',pharmacyviews.item_issue_report,name="item_issue_report"),
    path('item_return_report',pharmacyviews.item_return_report,name="item_return_report"),
    path('op_sale_report',pharmacyviews.op_sale_report,name="op_sale_report"),
    path('op_sale_report_details/<pk>',pharmacyviews.op_sale_report_details,name="op_sale_report_details"),
    path('op_sale_return_report',pharmacyviews.op_sale_return_report,name="op_sale_return_report"),
    path('vendor_payment_report',pharmacyviews.vendor_payment_report,name="vendor_payment_report"),
    path('expiry_item_list_report',pharmacyviews.expiry_item_list_report,name="expiry_item_list_report"),
    path('department_consumption_report',pharmacyviews.department_consumption_report,name="department_consumption_report"),
    path('stock_movement_report',pharmacyviews.stock_movement_report,name="stock_movement_report"),
    path('itemwise_purchase_report',pharmacyviews.itemwise_purchase_report,name="itemwise_purchase_report"),
    path('item_status_with_particular',pharmacyviews.item_status_with_particular,name="item_status_with_particular"),
    path('detail_item_status_report',pharmacyviews.detail_item_status_report,name="detail_item_status_report"),
    path('grn_report',pharmacyviews.grn_report,name="grn_report"),
    path('grn_item_detail/<pk>/',pharmacyviews.grn_item_detail,name="grn_item_detail"),
    path('stock_adjustement_report',pharmacyviews.stock_adjustement_report,name="stock_adjustement_report"),
    path('pharmacysale_summary_report',pharmacyviews.pharmacysale_summary_report,name="pharmacysale_summary_report"),
    path('pharmacysale_detail_report',pharmacyviews.pharmacysale_detail_report,name="pharmacysale_detail_report"),
    path('stock_transfer_report',pharmacyviews.stock_transfer_report,name="stock_transfer_report"),
    path('stock_tranfer_items_list/<pk>',pharmacyviews.stock_tranfer_items_list,name="stock_tranfer_items_list"),
    path('item_issue_report_details/<pk>',pharmacyviews.item_issue_report_details,name="item_issue_report_details"),
    path('purchase_item_report',pharmacyviews.purchase_item_report,name="purchase_item_report"),
    path('pharmacy_pl_report',pharmacyviews.pharmacy_pl_report,name="pharmacy_pl_report"),
    path('stock_ledger_report',pharmacyviews.stock_ledger_report,name="stock_ledger_report"),



#====================================================== Merging Code 29/03/2023==========================================
    path('list_cancel_bill', viewstestapp.list_cancel_bill, name="list_cancel_bill"),
    path('vitals_sign', viewstestapp.vitals_sign, name="vitals_sign"),


    path('location_master', viewstestapp.location_master, name='location_master'),
    path('edit_location_master/<pk>',viewstestapp.edit_location_master,name='edit_location_master'),

    # RIS
    path('RIS_pendinginvestigation',viewstestapp.RIS_pendinginvestigation,name='RIS_pendinginvestigation'),
    path('note_book/<pk>',viewstestapp.note_book,name='note_book'),
    path('RIS_report',viewstestapp.RIS_report,name='RIS_report'),
    path('RIS_report_print/<pk>',viewstestapp.RIS_report_print,name='RIS_report_print'),

    path('final_bill',viewstestapp.final_bill,name='final_bill'),
    path('template_master',viewstestapp.template_master,name='template_master'),
    path('radiology_template_master',viewstestapp.radiology_template_master,name='radiology_template_master'),
    path('lab_template_master',viewstestapp.lab_template_master,name='lab_template_master'),
    path('radiology_template_master_edit/<pk>',viewstestapp.radiology_template_master_edit,name='radiology_template_master_edit'),
    path('lab_template_master_edit/<pk>',viewstestapp.lab_template_master_edit,name='lab_template_master_edit'),

    path('appointment_table', viewstestapp.list_of_appointment, name='delete-appointment'),
    path('admin-dashboard',viewstestapp.patient_dashboard),
    path('new-appointment',viewstestapp.appointment_by_admin),
    path('choose-doctor',viewstestapp.choose_doctor),
    path('booked-slots',viewstestapp.booked_slots),
    path('successfully-booked',viewstestapp.successfully_booked),
    path('appointment_patient_search',viewstestapp.appointment_patient_search),
    path('permanent_access_master',viewstestapp.permanent_access_master,name = "permanent_access_master"),
    path('edit_permanent_access_master/<pk>/',viewstestapp.edit_permanent_access_master,name = "edit_permanent_access_master"),
    path('change_password', viewstestapp.change_password, name="change_password"),
    path('refered_bymaster', viewstestapp.refered_bymaster, name="refered_bymaster"),
    path('edit_refered_bymaster/<pk>',viewstestapp.edit_refered_bymaster,name = "edit_refered_bymaster"),

#====================================================== for dialysis 03/04/2023==========================================
    path('list_new_dialysis_patient', viewstestapp.list_new_dialysis_patient, name='list_new_dialysis_patient'),
    path('prescription_dialysis/<str:pk>', viewstestapp.prescription_dialysis, name='prescription_dialysis'),
    path('prescription_dialysis_update/<str:pk>', viewstestapp.prescription_dialysis_update, name='prescription_dialysis_update'),
    path('temp_access', viewstestapp.temp_access, name='temp_access'),
    path('prescription_dialysis_update1/<str:pk>',viewstestapp.prescription_dialysis_update1,name = "prescription_dialysis_update1"),
    path('temp_access_delete',viewstestapp.temp_access_delete,name = "temp_access_delete"),


    path('opd_print_view',viewstestapp.opd_print_view,name = "opd_print_view"),
    path('opd_print_credit/<pk>',viewstestapp.opd_print_credit,name = "opd_print_credit"),
    path('opd_print_cash/<pk>',viewstestapp.opd_print_cash,name = "opd_print_cash"),
    path('opd_temp_delete',viewstestapp.opd_temp_delete,name = "opd_temp_delete"),

    path('user_collection_summary',viewstestapp.user_collection_summary,name = "user_collection_summary"),
    path('relation_nhif',viewstestapp.relation_nhif,name = "relation_nhif"),
    path('edit_relation_nhif/<pk>',viewstestapp.edit_relation_nhif,name = "edit_relation_nhif"),
    path('delete_add_drugs',viewstestapp.delete_add_drugs,name = "delete_add_drugs"),
    path('perm_access_delete',viewstestapp.perm_access_delete,name = "perm_access_delete"),

    path('out_sourse_service',viewstestapp.out_sourse_service,name = "out_sourse_service"),

    path('post_dialysis_discharge/<str:uhid_visit>', viewstestapp.post_dialysis_discharge, name="post_dialysis_discharge"),
    path('list_of_post_dialysis',viewstestapp.list_of_post_dialysis,name='list_of_post_dialysis'),
    path('dialysis_dishcharge_report/<str:uhid_visit>',viewstestapp.dialysis_dishcharge_report,name='dialysis_dishcharge_report'),
    path('list_cl_patient',viewstestapp.list_cl_patient,name='list_cl_patient'),
    path('cl_patient_report/<str:uhid_visit>',viewstestapp.cl_patient_report,name='cl_patient_report'),

    path('pre_equipment_master',viewstestapp.pre_equipment_master,name='pre_equipment_master'),
    path('edit_pre_equipment_master/<pk>',viewstestapp.edit_pre_equipment_master,name='edit_pre_equipment_master'),
    path('sample_collection/<ptid>',viewstestapp.sample_collection,name='sample_collection'),

    path('opdbilling_details',viewstestapp.opdbilling_details,name='opdbilling_details'),
    path('opdbilling_list_details/<pk>',viewstestapp.opdbilling_list_details,name='opdbilling_list_details'),
    path('lab_inves_senses',viewstestapp.lab_inves_senses,name='lab_inves_senses'),

    path('tat_lab_report_all',viewstestapp.tat_lab_report_all,name='tat_lab_report_all'),
    path('tat_all_report_print/<pk>',viewstestapp.tat_all_report_print,name='tat_all_report_print'),

    path('cannulation_nurse',viewstestapp.cannulation_nurse,name='cannulation_nurse'),
    path('edit_cannulation_nurse/<pk>',viewstestapp.edit_cannulation_nurse,name='edit_cannulation_nurse'),
    #================ for Clinical Dialysis Patient =============================
    path('list_discharge_dialysis_patient',viewstestapp.list_discharge_dialysis_patient,name='list_discharge_dialysis_patient'),
    path('discharged_dialysis_patient',viewstestapp.discharged_dialysis_patient,name='discharged_dialysis_patient'),
    path('opd_add_service_delete/<pk>',viewstestapp.opd_add_service_delete,name='opd_add_service_delete'),

    path('opd_package_profile_temp/<serv>', viewstestapp.opd_package_profile_temp, name='opd_package_profile_temp'),

    path('daily_billing_report', views2testapp.daily_billing_report,name='daily_billing_report'),
    path('monthly_report', views2testapp.monthly_report,name='monthly_report'),
    path('service_charge_edit',views2testapp.service_charge_edit,name='service_charge_edit'),
    path('package_charge_edit',views2testapp.package_charge_edit,name='package_charge_edit'),
    path('profile_charge_edit',views2testapp.profile_charge_edit,name='profile_charge_edit'),
    path('per_hour_delete/<pk>/<id>',views2testapp.per_hour_delete,name='per_hour_delete'),

    path('discharge_medi_delete/<uhid_visit>/<id>',views2testapp.discharge_medi_delete,name='discharge_medi_delete'),
    path('discharge_prescription_delete/<uhid_visit>/<id>',views2testapp.discharge_prescription_delete,name='discharge_prescription_delete'),
    path('discharge_post_medi_delete/<uhid_visit>/<id>',views2testapp.discharge_post_medi_delete,name='discharge_post_medi_delete'),

    path('dialysis_report_chart/<pk>',views2testapp.dialysis_report_chart,name='dialysis_report_chart'),

    path('view_packages_services/<pid>',views2testapp.view_packages_services,name='view_packages_services'),
    path('opd_package_service_edit/<pid>',views2testapp.opd_package_service_edit,name='opd_package_service_edit'),
    path('opd_package_service_add/<serv>/<pid>',views2testapp.opd_package_service_add,name='opd_package_service_add'),
    path('opd_package_profile_add/<serv>/<pid>',views2testapp.opd_package_profile_add,name='opd_package_profile_add'),
    path('opd_service_delete/<pk>/<pid>',views2testapp.opd_service_delete,name='opd_service_delete'),

    path('final_lab_report/<pk>',viewstestapp.final_lab_report,name='final_lab_report'),
    path('PO_pending_editt',pharmacyviews.PO_pending_edit,name='PO_pending_edit'),
    path('previuos_dialysis_details',views2testapp.previuos_dialysis_details, name='previuos_dialysis_details'),

    path('lab_result_save/<pk>',viewstestapp.lab_result_save,name='lab_result_save'),
    path('lab_service_temp/<ptid>',viewstestapp.lab_service_temp,name='lab_service_temp'),
    path('lab_service_temp1/<ptid>',viewstestapp.lab_service_temp1,name='lab_service_temp1'),
    path('delete_lab_temp/<test_id>',viewstestapp.delete_lab_temp,name='delete_lab_temp'),
    path('nhif_unpaidbill_report', views2testapp.nhif_unpaidbill_report),

    path('lab_revenue_report',views2testapp.lab_revenue_report,name='lab_revenue_report'),
    path('lab_sales_report',views2testapp.lab_sales_report,name='lab_sales_report'),

    path('user_collection_summary_new',views2testapp.user_collection_summary_new,name='user_collection_summary_new'),

    path('list_cash_outstanding_amt',views2testapp.list_cash_outstanding_amt,name='list_cash_outstanding_amt'),
    path('cash_settle/<pk>',views2testapp.cash_settle,name='cash_settle'),

#========================== OPD BILL EDITTING ====================================================
    path('list_all_bill', views2testapp.list_all_bill, name='list_all_bill'),
    path('update_opd_bill/<pk>', views2testapp.update_opd_bill, name='update_opd_bill'),
    path('update_opd_bill_search/<pk>/<str:serv>', views2testapp.update_opd_bill, name='update_opd_bill_search'),
    path('sub_service_removing/<pk>/<id>', views2testapp.sub_service_removing, name='sub_service_removing'),
    path('search_services', views2testapp.search_services, name='search_services'),
    path('temp_service_deleting/<pk>/<id>', views2testapp.temp_service_deleting, name='temp_service_deleting'),
    path('update_bill_main/<pk>', views2testapp.update_bill_main, name='update_bill_main'),
#=================================== END ==========================================================
    path('dialys_prescription_list',views2testapp.dialys_prescription_list,name='dialys_prescription_list'),

    path('main_dashboard',views2testapp.main_dashboard,name="main_dashboard"),
    path('doctor_request',viewstestapp.doctor_request,name="doctor_request"),
    path('doctor_confirmation/<pk>/',viewstestapp.doctor_confirmation,name="doctor_confirmation"),
    path('doctor_notes',viewstestapp.doctor_notes,name='doctor_notes'),
    path('doctornotes_print/<pk>',viewstestapp.doctornotes_print,name='doctornotes_print'),
    path('doctornotes_view',viewstestapp.doctornotes_view,name='doctornotes_view'),
    path('refferal_dialysis_patient',viewstestapp.refferal_dialysis_patient,name='refferal_dialysis_patient'),
    path('refferal_dialysisprint/<pk>',viewstestapp.refferal_dialysisprint,name='refferal_dialysisprint'),
    path('refferal_dialysis_view',viewstestapp.refferal_dialysis_view,name='refferal_dialysis_view'),
    path('preprocedural_checklist',viewstestapp.preprocedural_checklist,name='preprocedural_checklist'),
    path('preprocedural_checklistprint/<pk>',viewstestapp.preprocedural_checklistprint,name='preprocedural_checklistprint'),
    path('preprocedural_checklist_view',viewstestapp.preprocedural_checklist_view,name='preprocedural_checklist_view'),
    path('informed_consent_form',viewstestapp.informed_consent_form,name='informed_consent_form'),
    path('informed_consentprint/<pk>',viewstestapp.informed_consentprint,name='informed_consentprint'),
    path('informed_consent_view',viewstestapp.informed_consent_view,name='informed_consent_view'),
    path('consent_kidney_dialysis',viewstestapp.consent_kidney_dialysis,name='consent_kidney_dialysis'),
    path('consent_kidneyprint/<pk>',viewstestapp.consent_kidneyprint,name='consent_kidneyprint'),
    path('consent_kidney_view',viewstestapp.consent_kidney_view,name='consent_kidney_view'),

###### Incidents Module  ###########
    path('incident_type',views2testapp.incident_type,name="incident_type"),
    path('incident_dashboard',views2testapp.incident_dashboard,name="incident_dashboard"),
    path('contributing_factor',views2testapp.contributing_factor,name="contributing_factor"),
    path('incident_creation_form',views2testapp.incident_creation_form,name="incident_creation_form"),
    path('investigation_form',views2testapp.investigation_form,name="investigation_form"),
    path('investigation_creation_form/<pk>',views2testapp.investigation_creation_form,name="investigation_creation_form"),
    path('incident_list_report',views2testapp.incident_list_report,name="incident_list_report"),
    path('investigation_list/<pk>',views2testapp.investigation_list,name="investigation_list"),
    path('detailed_incident_list_report',views2testapp.detailed_incident_list_report,name="detailed_incident_list_report"),
    #======================= for clinical management =====================================
    path('current_report/<pk>',views2testapp.current_report,name='current_report'),
    path('final_lab_report_clinical/<pk>',views2testapp.final_lab_report_clinical,name='final_lab_report_clinical'),

    path('dr_schedule_report',views2testapp.dr_schedule_report,name='dr_schedule_report'),
    path('discount_report',views2testapp.discount_report,name='discount_report'),
    path('auth_person_disc',views2testapp.auth_person_disc,name='auth_person_disc'),      
    # Usermanagement
    path('screen_access_view',usermanagement.screen_access_view,name='screen_access_view'), 
    path('screen_access',usermanagement.screen_access,name='screen_access'),
    path('screen_access_edit/<pk>',usermanagement.screen_access_edit,name='screen_access_edit'),  
]