# Generated by Django 4.2.5 on 2023-11-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_branchrestrict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchRestrict',
        ),
    ]
