# Generated by Django 4.2.5 on 2023-11-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_delete_branchrestrict'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='public.client',
        ),
    ]
