# Generated by Django 4.2.5 on 2023-11-30 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_client_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
    ]
