# Generated by Django 4.2.7 on 2023-12-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_createuser_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchRestrict',
        ),
    ]
